# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-01 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber_trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubertrip',
            name='end_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ubertrip',
            name='start_address',
            field=models.CharField(max_length=200),
        ),
    ]
